services:
  genotif-website:
    build: .
    container_name: genotif_web_prototype
    restart: always
    ports:
      - "3000:3000"
    networks:
      - server-network

networks:
  server-network:
    external: true
