name: Deploy Web Geno

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # Ini menunjuk ke Runner di server kamu

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Deploy Script
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
